services:
  - type: web
    name: pdf-query-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # ensures dynamic PORT usage
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        value: YOUR_API_KEY_HERE
      - key: PINECONE_API_KEY
        value: YOUR_PINECONE_KEY_HERE
