services:
  - type: web
    name: pdf-query-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PINECONE_REGION
      - value: us-east-1
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        value: YOUR_GROQ_KEY
      - key: PINECONE_API_KEY
        value: YOUR_PINECONE_KEY
      - key: PINECONE_INDEX_NAME
        value: YOUR_INDEX_NAME
          # <-- ADD THIS LINE!
